services:
  - type: web
    name: ai-chat-bot
    env: python
    region: ohio
    buildCommand: |
      pip install -r requirements.txt
      chmod +x start.sh
    startCommand: ./start.sh
    autoDeploy: true
    plan: free
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health 