services:
  - type: worker
    name: ai-chat-bot
    env: python
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    plan: free
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.8.0
    healthCheckPath: /health 